### PR TITLE
test: cpe, executor, model, project, validator, and routing

### PR DESCRIPTION
**Pull request by EricSommerhalder**
Resolves DEV-1808

### CODE REVIEW

**Comment by mdelez** [comment]
Screenshot 2023-03-30 at 16 45 07

Just a preliminary finding. These `binding` console errors should be dealt with before they spiral out of control like they did in the DSP-APP.

**Comment by EricSommerhalder** [comment]
We could consider adding something like this so console.warn() and console.error() calls actually make the test fail:
function patchConsole(): void {
    console.warn = function(message?: any, ...optionalParams: any[]): void {
        const params = optionalParams ? `\nParams: ${optionalParams}` : '';
        fail(`Test contained console warning:\n${message}${params}`);
    };
    console.error = function(message?: any, ...optionalParams: any[]): void {
        const params = optionalParams ? `\nParams: ${optionalParams}` : '';
        fail(`Test contained console error:\n${message}${params}`);
    };
}

**Comment by mdelez** [comment]
> We could consider adding something like this so console.warn() and console.error() calls actually make the test fail: function patchConsole(): void { console.warn = function(message?: any, ...optionalParams: any[]): void { const params = optionalParams ? `\nParams: ${optionalParams}` : ''; fail(`Test contained console warning:\n${message}${params}`); }; console.error = function(message?: any, ...optionalParams: any[]): void { const params = optionalParams ? `\nParams: ${optionalParams}` : ''; fail(`Test contained console error:\n${message}${params}`); }; }

We could but I think some console errors are inevitable when testing

**Review by mdelez — APPROVED** [review]
thank you very much good sir

**Pull request merged**
